version: '3.8'

services:
  photoeditor-server:
    container_name: photoeditor-server
    image: photoeditor-server:latest
    volumes:
      - ${HOST_CERT_FOLDER}:${CONTAINER_CERT_FOLDER}
    build: .
    environment:
      DOCKER_ENV: "true"
      PRIVKEY_PATH: ${PRIVKEY_PATH}
      CERT_PATH: ${CERT_PATH}
      SERVER_PORT: ${SERVER_PORT:-3000}
      MONGODB_DB: ${MONGODB_DB:-userLogs}
      MONGODB_PORT: 27017
      MONGODB_USERNAME: ${MONGODB_USERNAME:-admin}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      B2_ACCOUNT_ID: ${B2_ACCOUNT_ID}
      B2_APPLICATION_KEY: ${B2_APPLICATION_KEY}
      B2_BUCKET_ID: ${B2_BUCKET_ID}
      MONGODB_HOST: mongodb
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      GITHUB_OWNER: BTI-US
      GITHUB_REPO: ${GITHUB_REPO:-PhotoEditor}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      RELEASE_NAME: ${RELEASE_NAME:-release.apk}
      INFURA_PROJECT_ID: ${INFURA_PROJECT_ID}
      CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
      ETHEREUM_NETWORK: ${ETHEREUM_NETWORK:-mainnet}
      EXPIRATION_TIME_PERIOD: ${EXPIRATION_TIME_PERIOD:-1}
    ports:
      - "${SERVER_PORT:-3000}:${SERVER_PORT:-3000}"
    depends_on:
      - mongodb
    restart: always

  mongodb:
    container_name: mongodb-photoeditor
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - "/root/mongodb-image:/data/db"
    restart: always
